### ISSUE TITLE
Bug: key error __meta

### ISSUE THREAD

**Issue by Fashizel** [atmaranto/ComfyUI-SaveAsScript#3]
Im getting 

`Traceback (most recent call last):
  File "/root/custom_nodes/ComfyUI-SaveAsScript/__init__.py", line 46, in save_as_script
    ComfyUItoPython(workflow=workflow, output_file=sio)
  File "/root/custom_nodes/ComfyUI-SaveAsScript/comfyui_to_python.py", line 530, in __init__
    self.execute()
  File "/root/custom_nodes/ComfyUI-SaveAsScript/comfyui_to_python.py", line 557, in execute
    generated_code = code_generator.generate_workflow(load_order, queue_size=self.queue_size)
  File "/root/custom_nodes/ComfyUI-SaveAsScript/comfyui_to_python.py", line 216, in generate_workflow
    arg_inputs.append((input_var, f"Argument {i}, input `{input}` for node \\\"{data['_meta'].get('title', class_type)}\\\" id {idx}"))
KeyError: '_meta'
`

When trying to export using the GUI. Took a look in the code but im not sure what is the issue, no savy with comfyui nodes. 

Thanks!

**Comment by atmaranto** [comment]
Hmm... looks like one of the nodes doesn't have metadata for some reason. Should be a pretty simple fix, but I won't be able to test it.

**Comment by atmaranto** [comment]
I'll try to get something in for this later today.

**Comment by atmaranto** [comment]
@Fashizel, try it now.

**Comment by atmaranto** [comment]
Closing this issue for now.

**Comment by Fashizel** [comment]
Thanks !
